services:

   postgres:
      image: postgres:16.3
      environment:
        - POSTGRES_PASSWORD=alfresco
        - POSTGRES_USER=alfresco
        - POSTGRES_DB=alfresco
      command: postgres -c max_connections=300 -c log_min_messages=LOG

   alfresco:
      depends_on:
        - postgres
      image: acosix-utility-repo-test:local
      build:
         context: ./
         dockerfile: Dockerfile-ACS-7.4
      volumes:
        - alfresco_data:/usr/local/tomcat/alf_data
      environment:
         JAVA_OPTS: >-
           -Ddb.driver=org.postgresql.Driver
           -Ddb.username=alfresco
           -Ddb.password=alfresco
           -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
           -Dencryption.keystore.type=JCEKS
           -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
           -Dencryption.keyAlgorithm=DESede
           -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
           -Dmetadata-keystore.password=mp6yc0UD9e
           -Dmetadata-keystore.aliases=metadata
           -Dmetadata-keystore.metadata.password=oKIWzVdEdA
           -Dmetadata-keystore.metadata.algorithm=DESede
           -Dsolr.host=solr6
           -Dsolr.port=8983
           -Dsolr.secureComms=secret
           -Dsolr.sharedSecret=secret  
           -Dsolr.base.url=/solr
           -Dindex.subsystem.name=solr6
           -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
           -Dlocal.transform.service.enabled=true
           -DlocalTransform.core-aio.url=http://transform-core-aio:8090
           -Dacosix-utility.email.inboundSMTP.subsystemEnhancement.enabled=true
           -Dacosix-utility.email.server.enhancements.enabled=true
           -Dacosix-utility.email.handler.folder.enhancements.enabled=true
           -Demail.handler.folder.overwriteDuplicates=false
           -Demail.server.enabled=true
           -Dcsrf.filter.enabled=false
           -Dfile.encoding=UTF-8
           -Djava.net.preferIPv4Stack=true
           -Xms2G -Xmx2G
           -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication
           -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
      ports:
        - 8080:8080
        - 10025:25

   share:
      image: acosix-utility-share-test:local
      build:
         context: ./
         dockerfile: Dockerfile-Share-7.4
      environment:
         REPO_HOST: alfresco
         REPO_PORT: 8080
         JAVA_OPTS: >-
           -Xms500m -Xmx500m
           -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication
           -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
      ports:
        - 8180:8080

   solr6:
      image: alfresco/alfresco-search-services:2.0.10
      environment:
         SOLR_ALFRESCO_HOST: alfresco
         SOLR_ALFRESCO_PORT: 8080
         SOLR_SOLR_HOST: solr6
         SOLR_SOLR_PORT: 8983
         SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco
         ALFRESCO_SECURE_COMMS: secret
         JAVA_TOOL_OPTIONS: -Dalfresco.secureComms.secret=secret
         SOLR_JAVA_MEM: -Xms2g -Xmx2g
      ports:
        - 8083:8983

   activemq:
      image: alfresco/alfresco-activemq:5.17-jre17-rockylinux8

   transform-core-aio:
      image: alfresco/alfresco-transform-core-aio:5.1.2
      environment:
         JAVA_OPTS: " -Xms256m -Xmx1536m"
         ACTIVEMQ_URL: nio://activemq:61616

volumes:
   alfresco_data:
