on: [push]
jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: setup-java8
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: |
              8
              17
            cache: maven
      - run: mvn -version
      - run: mvn --batch-mode --update-snapshots verify
